image: ruby:2.1

pages:
  script:
  - gem install jekyll
  - gem i rubygems-update -v '<3' && update_rubygems
  - gem install bundler	  - gem install bundler
  artifacts:
    paths:
    - public
  only:
  - master